#pragma config(Sensor, S2,     ,               sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    int x = 50;

    while (true)
    {
        if (SensorValue[S2] > 75)
        {
          	setMotorSpeed(motorB, x);
        		setMotorSpeed(motorC, x);

        		sleep(100);

            if (x == 50)
            {
                x = 0;
            }
            else
            {
                x = 50;
            }
        }
    }
}
