#pragma config(Sensor, S4, colorSensor, sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
    int colorValue = SensorValue[S4];
    int direction, duration;

    while (true) {
        colorValue = SensorValue[S4];
        displayTextLine(2, "Colour: %d", colorValue);

        if (colorValue < 25) {
            setMotorSpeed(motorB, 15);
            setMotorSpeed(motorC, 15);

        } else {
        		if (colorValue > 40)
              	{
              			setMotorSpeed(motorB, 20);
           					setMotorSpeed(motorC, 20);
           					sleep(1100);
              			stopAllTasks();
              	}

            direction = 1;
            duration = 10;
            while (colorValue >= 25 && colorValue <= 40) {

            		setMotorSpeed(motorB, -20 * direction);
                setMotorSpeed(motorC,  20 * direction);
                sleep(duration);

                direction = -direction;
                duration += 20;

                setMotorSpeed(motorB, 0);
                setMotorSpeed(motorC, 0);
                sleep(50);

                colorValue = SensorValue[S4];
                displayTextLine(2, "Colour: %d", colorValue);

            }
        sleep(50);
        }
    }
}
