#pragma config(Sensor, S4, colorSensor, sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

task main()
{
int count = 0;
int r, g, b;
while (true) {
setMotorSpeed(motorB, 15);
setMotorSpeed(motorC, 15);
getColorRGB(colorSensor, r, g, b);
displayTextLine(2, "Colour: %d %d %d", r, g, b);

if (r > 10 && r < 20 && g > 10 && g < 20 && b > 12 && b < 22) {
	playImmediateTone(262, 30);
	sleep(250);
} else if (r > 68 && r < 78 && g > 40 && g < 50 && b > 5 && b < 15) {
	playImmediateTone(330, 30);
	sleep(250);
} else if (r > 75 && r < 85 && g > 10 && g < 20 && b > 0 && b < 10) {
	playImmediateTone(392, 30);
	sleep(250);
} else if (r > 30 && r < 40 && g > 30 && g < 40 && b > 15 && b < 25) {
	playImmediateTone(349, 30);
	sleep(250);
} else if (r > 60 && r < 70 && g > 4 && g < 14 && b > 0 && b < 10) {
	playImmediateTone(294, 30);
	sleep(250);
}

count += 1;

if (count == 430) {
	break;
}
sleep(10);
}

}
